
- name: check log directory
  stat: path=/tmp/pb-build-phpweb-log
  register: logdir

- name: create log directory
  become: True
  file: path=/tmp/pb-build-phpweb-log
        state=directory
        owner=root
        group=root
        mode=0755
  when: not logdir.stat.exists

### webserv setting ###
- name: check webserv flag
  stat: path=/tmp/pb-build-phpweb-log/webserv
  register: webserv_flag

- name: install latest version of apache server and php
  yum: name={{ item }}
       state=latest
  with_items:
    - httpd
    - php
    - php-pear
 
- name: start apache server
  become: yes
  command: systemctl start httpd
  when: not webserv_flag.stat.exists

- name: restart apache server
  become: yes
  command: systemctl restart httpd

- name: enable apache server
  become: yes
  command: systemctl enable httpd

- name: create webserv flag
  command: touch /tmp/pb-build-phpweb-log/webserv
  when: not webserv_flag.stat.exists


### firewall setting ###
- name: allow http packet
  firewalld: service=http
             permanent=true
             state=enabled

- name: commit firewalld config
  become: yes
  command: systemctl restart firewalld 
